Kermesse\KermesseBundle\Entity\Products:
    type: entity
    table: products
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
        price:
            type: decimal
            nullable: false
            precision: 10
            scale: 4
            comment: ''
            default: '0.0000'
    lifecycleCallbacks: {  }
